geometry_msgs/Vector3Stamped left_front
geometry_msgs/Vector3Stamped right_front
geometry_msgs/Vector3Stamped left_middle
geometry_msgs/Vector3Stamped right_middle
geometry_msgs/Vector3Stamped left_rear
geometry_msgs/Vector3Stamped right_rear
---
bool success
